### ISSUE TITLE
Adding new tags

### ISSUE THREAD

**Issue by rrrliu** [codebase-berkeley/cofed#39]
See Bianca's comment below! Note that you can choose to POST/DELETE every time a tag is deleted, or combine this into the existing /api/coops/:coopId PUT request.

**Comment by leebianca** [comment]
- Follow the [Figma](https://www.figma.com/file/G2fICWO4MvkrXh9PTC7e52/Codebase-Mentored-x-CoFED?node-id=0%3A1) so that coops are able to add tags to their profile. Use the [Material UI Modal](https://material-ui.com/components/modal/) component to create the modal (pop-up window).
- To render the list of tags in the modal, make a GET endpoint to retrieve the tags that the coop isn't already associated with.
- When a user clicks on a tag in the modal, make a POST request to insert the coop/tag association in the `tags` table.
- When a user deletes a tag from their profile, make a DELETE request to delete the coop/tag association from the `tags` table.

**Comment by ilyues** [comment]
<img width="1223" alt="Screen Shot 2020-11-18 at 10 41 42 PM" src="https://user-images.githubusercontent.com/61926689/99513247-46ff6f80-29ef-11eb-8221-b345a5f1ba60.png">

could this be an appropriate modal ???? it's just v similar to the filters page,,

**Comment by rrrliu** [comment]
yooooo pretty fire i like -- that way you can reuse the Filter component from FiltersPage. maybe this could be used for deleting tags too (replacing the original "x"s we had) and then change the "Add" button to "Save"

**Comment by leebianca** [comment]
oo i like it! +1 to richard's comment and we could prob also take out the inner box around the filter selection too

**Comment by ilyues** [comment]
@rrrliu  o i didn't think ab using it for deleting tags but that would make sense ?! but aw noo all of zaid and erics css efforts to make the red crosses on the profile tags ... also i made it 'add' (maybe 'change' or 'edit' if we use it to delete too?) instead of 'save' because there's a general 'save' button for editing profile, and i thought it might make more sense to make the post request only once that general save is clicked? 

also @leebianca theres a second border j bc if the dropdowns overflow the div i thought it would make sense to outline the scrollable div for visual clarity bc the modal title and button at the bottom dont scroll with it o: 

but lmk what yall think
